# Generated by Django 6.0.6 on 2026-07-02 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=150, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='courses.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='departments.department')),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
    ]
